# platform = multi_platform_fedora,Red Hat Enterprise Linux 7,Red Hat Enterprise Linux 8
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Ensure that chronyd is running under chrony user account
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82878-0
    - chronyd_run_as_chrony_user
    - configure_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Detect if file /etc/sysconfig/chronyd is not empty or missing
      find:
        path: /etc/sysconfig/
        patterns: chronyd
        contains: ^([\s]*OPTIONS=["]?[^"]*)("?)
      register: chronyd_file
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"chrony" in ansible_facts.packages'

    - name: Remove any previous configuration of user used to run chronyd process
      replace:
        path: /etc/sysconfig/chronyd
        regexp: \s*-u\s+\w+\s*
        replace: ' '
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"chrony" in ansible_facts.packages'
        - chronyd_file is defined and chronyd_file.matched > 0

    - name: Correct existing line in /etc/sysconfig/chronyd to run chronyd as chrony
        user
      lineinfile:
        path: /etc/sysconfig/chronyd
        regexp: ^([\s]*OPTIONS=["]?[^"]*)("?)
        line: \1 -u chrony\2
        state: present
        backrefs: true
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"chrony" in ansible_facts.packages'
        - chronyd_file is defined and chronyd_file.matched > 0

    - name: Insert correct line into /etc/sysconfig/chronyd ensuring chronyd runs
        as chrony user
      lineinfile:
        path: /etc/sysconfig/chronyd
        line: OPTIONS="-u chrony"
        state: present
        create: true
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"chrony" in ansible_facts.packages'
        - chronyd_file is defined and chronyd_file.matched == 0
