# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Verify Permissions on Backup group File
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-83482-0
    - configure_strategy
    - file_permissions_backup_etc_group
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
  tasks:

    - name: Test for existence /etc/group-
      stat:
        path: /etc/group-
      register: file_exists

    - name: Ensure permission 0644 on /etc/group-
      file:
        path: /etc/group-
        mode: '0644'
      when: file_exists.stat is defined and file_exists.stat.exists
