# platform = multi_platform_fedora,Red Hat Enterprise Linux 7,Red Hat Enterprise Linux 8,multi_platform_ol
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Set Up a Private Namespace in PAM Configuration
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-83743-5
    - enable_pam_namespace
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
    - restrict_strategy
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Make changes to /etc/pam.d/login
      lineinfile:
        path: /etc/pam.d/login
        create: false
        regexp: ^\s*session\s+required\s+pam_namespace.so\s*$
        line: session    required     pam_namespace.so
        state: present
      when: '"pam" in ansible_facts.packages'
