# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Install iptables Package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82983-8
    - NIST-800-53-CM-6(a)
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - package_iptables_installed
  tasks:

    - name: Ensure iptables is installed
      package:
        name: iptables
        state: present
