# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Disable Automatic Bug Reporting Tool (abrtd)
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82027-4
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - disable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_abrtd_disabled
  tasks:

    - name: Disable service abrtd
      block:

        - name: Gather the service facts
          service_facts: null

        - name: Disable service abrtd
          systemd:
            name: abrtd.service
            enabled: 'no'
            state: stopped
            masked: 'yes'
          when: '"abrtd.service" in ansible_facts.services'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Unit Socket Exists - abrtd.socket
      command: systemctl list-unit-files abrtd.socket
      args:
        warn: false
      register: socket_file_exists
      changed_when: false
      ignore_errors: true
      check_mode: false
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Disable socket abrtd
      systemd:
        name: abrtd.socket
        enabled: 'no'
        state: stopped
        masked: 'yes'
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"abrtd.socket" in socket_file_exists.stdout_lines[1]'
