# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel
# reboot = false
# strategy = configure
# complexity = low
# disruption = medium
- name: Ensure PAM Enforces Password Requirements - Authentication Retry Prompts Permitted
    Per-Session
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_password_pam_retry: '3'
  tags:
    - CCE-27160-1
    - CJIS-5.5.3
    - DISA-STIG-RHEL-07-010119
    - NIST-800-53-AC-7(a)
    - NIST-800-53-CM-6(a)
    - NIST-800-53-IA-5(4)
    - accounts_password_pam_retry
    - configure_strategy
    - low_complexity
    - medium_disruption
    - medium_severity
    - no_reboot_needed
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Set Password Retry Prompts Permitted Per-Session - system-auth (change)
      replace:
        dest: /etc/pam.d/system-auth
        regexp: (^.*\spam_pwquality.so\s.*retry\s*=\s*)(\S+)(.*$)
        replace: \g<1>{{ var_password_pam_retry }}\g<3>
      when: '"pam" in ansible_facts.packages'

    - name: Set Password Retry Prompts Permitted Per-Session - system-auth (add)
      replace:
        dest: /etc/pam.d/system-auth
        regexp: ^.*\spam_pwquality.so\s(?!.*retry\s*=\s*).*$
        replace: \g<0> retry={{ var_password_pam_retry }}
      when: '"pam" in ansible_facts.packages'
