# platform = Red Hat Enterprise Linux 7,Red Hat Enterprise Linux 8,multi_platform_fedora,multi_platform_rhv,multi_platform_ol
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Configure opensc Smart Card Drivers
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_smartcard_drivers: cac
  tags:
    - CCE-80565-5
    - NIST-800-53-CM-6(a)
    - NIST-800-53-IA-2(1)
    - NIST-800-53-IA-2(11)
    - NIST-800-53-IA-2(2)
    - NIST-800-53-IA-2(3)
    - NIST-800-53-IA-2(4)
    - NIST-800-53-IA-2(6)
    - NIST-800-53-IA-2(7)
    - PCI-DSS-Req-8.3
    - configure_opensc_card_drivers
    - configure_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
  tasks:

    - name: Check existence of opensc conf
      stat:
        path: /etc/opensc-{{ ansible_architecture }}.conf
      register: opensc_conf_cd
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Configure smartcard driver block
      block:

        - name: Check if card_drivers is defined
          command: /usr/bin/opensc-tool -G app:default:card_drivers
          changed_when: false
          register: card_drivers

        - name: Configure opensc Smart Card Drivers
          command: |
            /usr/bin/opensc-tool -S app:default:card_drivers:{{ var_smartcard_drivers }}
          when:
            - card_drivers.stdout != var_smartcard_drivers
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - opensc_conf_cd.stat.exists
