# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = true
# strategy = restrict
# complexity = medium
# disruption = low
- name: Extend Audit Backlog Limit for the Audit Daemon
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82156-1
    - NIST-800-53-CM-6(a)
    - grub2_audit_backlog_limit_argument
    - low_disruption
    - medium_complexity
    - medium_severity
    - reboot_required
    - restrict_strategy
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: check audit_backlog_limit argument exists
      command: grep 'GRUB_CMDLINE_LINUX.*audit_backlog_limit=' /etc/default/grub
      failed_when: false
      register: argcheck
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'

    - name: replace existing audit_backlog_limit argument
      replace:
        path: /etc/default/grub
        regexp: audit_backlog_limit=\w+
        replace: audit_backlog_limit=8192
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'
        - argcheck.rc == 0

    - name: add audit_backlog_limit argument
      replace:
        path: /etc/default/grub
        regexp: (GRUB_CMDLINE_LINUX=.*)"
        replace: \1 audit_backlog_limit=8192"
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'
        - argcheck.rc != 0

    - name: update bootloader menu
      command: /sbin/grubby --update-kernel=ALL --args="audit_backlog_limit=8192"
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'
