# platform = Oracle Linux 7,Red Hat Enterprise Linux 7,Red Hat OpenShift Container Platform 4
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Install the dracut-fips Package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80358-5
    - CJIS-5.10.1.2
    - NIST-800-171-3.13.11
    - NIST-800-171-3.13.8
    - NIST-800-53-CM-6(a)
    - NIST-800-53-IA-7
    - NIST-800-53-SC-12
    - NIST-800-53-SC-12(2)
    - NIST-800-53-SC-12(3)
    - NIST-800-53-SC-13
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - package_dracut-fips_installed
  tasks:

    - name: Ensure dracut-fips is installed
      package:
        name: dracut-fips
        state: present
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - ansible_distribution == 'RedHat'
