# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Disable the polyinstantiation_enabled SELinux Boolean
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_polyinstantiation_enabled: 'false'
  tags:
    - CCE-82305-4
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - sebool_polyinstantiation_enabled
  tasks:

    - name: Ensure libsemanage-python installed
      package:
        name: libsemanage-python
        state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Set SELinux boolean polyinstantiation_enabled accordingly
      seboolean:
        name: polyinstantiation_enabled
        state: '{{ var_polyinstantiation_enabled }}'
        persistent: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
