# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Configure the selinuxuser_direct_dri_enabled SELinux Boolean
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_selinuxuser_direct_dri_enabled: 'true'
  tags:
    - CCE-82311-2
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - sebool_selinuxuser_direct_dri_enabled
  tasks:

    - name: Ensure libsemanage-python installed
      package:
        name: libsemanage-python
        state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Set SELinux boolean selinuxuser_direct_dri_enabled accordingly
      seboolean:
        name: selinuxuser_direct_dri_enabled
        state: '{{ var_selinuxuser_direct_dri_enabled }}'
        persistent: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
