# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Disable the selinuxuser_share_music SELinux Boolean
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_selinuxuser_share_music: 'false'
  tags:
    - CCE-82321-1
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - sebool_selinuxuser_share_music
  tasks:

    - name: Ensure libsemanage-python installed
      package:
        name: libsemanage-python
        state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Set SELinux boolean selinuxuser_share_music accordingly
      seboolean:
        name: selinuxuser_share_music
        state: '{{ var_selinuxuser_share_music }}'
        persistent: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
