# platform = multi_platform_fedora,multi_platform_rhel,multi_platform_ol
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Appropriate Action Must be Setup When the Internal Audit Event Queue is Full
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-88073-2
    - DISA-STIG-RHEL-07-030210
    - NIST-800-53-AU-4(1)
    - auditd_overflow_action
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
  tasks:

    - name: Appropriate Action Must be Setup When the Internal Audit Event Queue is
        Full
      block:

        - name: Check for duplicate values
          lineinfile:
            path: /etc/audit/auditd.conf
            create: false
            regexp: (?i)^\s*overflow_action\s*=\s*
            state: absent
          check_mode: true
          changed_when: false
          register: dupes

        - name: Deduplicate values from /etc/audit/auditd.conf
          lineinfile:
            path: /etc/audit/auditd.conf
            create: false
            regexp: (?i)^\s*overflow_action\s*=\s*
            state: absent
          when: dupes.found is defined and dupes.found > 1

        - name: Insert correct line to /etc/audit/auditd.conf
          lineinfile:
            path: /etc/audit/auditd.conf
            create: false
            regexp: (?i)^\s*overflow_action\s*=\s*
            line: overflow_action = syslog
            state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
