# platform = multi_platform_sle,Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_wrlinux
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Ensure PAM Displays Last Logon/Access Notification
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-27275-7
    - CJIS-5.5.2
    - DISA-STIG-RHEL-07-040530
    - NIST-800-53-AC-9(1)
    - NIST-800-53-CM-6(a)
    - PCI-DSS-Req-10.2.4
    - configure_strategy
    - display_login_attempts
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Check if pam_lastlog.so is set
      lineinfile:
        path: /etc/pam.d/postlogin
        regexp: ^\s*(session)(\s+)[^\s]+(\s+)(pam_lastlog\.so)(\s+)(.*)
        state: absent
      check_mode: true
      changed_when: false
      register: pam_lastlog_exists
      when: '"pam" in ansible_facts.packages'

    - name: Make sure pam_lastlog.so control is required
      replace:
        path: /etc/pam.d/postlogin
        regexp: ^\s*(session)(\s+)[^\s]+(\s+)(pam_lastlog\.so)(\s+)(.*)
        replace: \1\2required\3\4\5\6
      register: control_update_result
      when: '"pam" in ansible_facts.packages'

    - name: Add control for pam_lastlog.so module
      lineinfile:
        path: /etc/pam.d/postlogin
        line: session required pam_lastlog.so showfailed
      when:
        - '"pam" in ansible_facts.packages'
        - not pam_lastlog_exists.found
      register: add_new_pam_lastlog_control_result

    - name: Add 'showfailed' arg to pam_lastlog.so module
      pamd:
        name: postlogin
        type: session
        control: required
        module_path: pam_lastlog.so
        module_arguments: showfailed
        state: args_present
      when:
        - '"pam" in ansible_facts.packages'
        - not add_new_pam_lastlog_control_result.changed

    - name: Remove 'silent' arg for pam_lastlog.so module
      pamd:
        name: postlogin
        type: session
        control: required
        module_path: pam_lastlog.so
        module_arguments: silent
        state: args_absent
      when:
        - '"pam" in ansible_facts.packages'
        - not add_new_pam_lastlog_control_result.changed
