# platform = multi_platform_sle,Red Hat Enterprise Linux 7
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Verify Only Root Has UID 0
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82054-8
    - DISA-STIG-RHEL-07-020310
    - NIST-800-171-3.1.1
    - NIST-800-171-3.1.5
    - NIST-800-53-AC-6(5)
    - NIST-800-53-IA-2
    - NIST-800-53-IA-4(b)
    - accounts_no_uid_except_zero
    - high_severity
    - low_complexity
    - low_disruption
    - no_reboot_needed
    - restrict_strategy
  tasks:

    - name: get all /etc/passwd file entries
      getent:
        database: passwd
        split: ':'

    - name: lock the password of the user accounts other than root with uid 0
      command: passwd -l {{ item.key }}
      loop: '{{ getent_passwd | dict2items | rejectattr(''key'', ''search'', ''root'')
        | list }}'
      when: item.value.1  == '0'
