# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol
# reboot = false
# strategy = unknown
# complexity = low
# disruption = medium
- name: Disable GDM Guest Login
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80105-0
    - DISA-STIG-RHEL-07-010450
    - NIST-800-171-3.1.1
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - NIST-800-53-IA-2
    - gnome_gdm_disable_guest_login
    - high_severity
    - low_complexity
    - medium_disruption
    - no_reboot_needed
    - unknown_strategy
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Disable GDM Guest Login
      ini_file:
        dest: /etc/gdm/custom.conf
        section: daemon
        option: TimedLoginEnable
        value: 'false'
        no_extra_spaces: true
        create: true
      when:
        - '"gdm" in ansible_facts.packages'
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
