# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol
# reboot = false
# strategy = unknown
# complexity = low
# disruption = medium
- name: Configure SSSD LDAP Backend to Use TLS For All Transactions
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80546-5
    - DISA-STIG-RHEL-07-040180
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - high_severity
    - low_complexity
    - medium_disruption
    - no_reboot_needed
    - sssd_ldap_start_tls
    - unknown_strategy
  tasks:

    - name: Test for id_provider different than Active Directory (ad)
      command: grep -qzosP '[[:space:]]*\[domain\/[^]]*]([^(\n)]*(\n)+)+?[[:space:]]*id_provider[[:space:]]*=[[:space:]]*((?i)ad)[[:space:]]*$'
        /etc/sssd/sssd.conf
      register: test_id_provider
      ignore_errors: true
      changed_when: false
      check_mode: false
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Test for domain group
      command: grep '\s*\[domain\/[^]]*]' /etc/sssd/sssd.conf
      register: test_grep_domain
      ignore_errors: true
      changed_when: false
      check_mode: false
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Add default domain group and set ldap_id_use_start_tls in sssd configuration
        (if no domain there)
      ini_file:
        path: /etc/sssd/sssd.conf
        section: '{{ item.section }}'
        option: '{{ item.option }}'
        value: '{{ item.value }}'
      with_items:
        - section: sssd
          option: domains
          value: default
        - section: domain/default
          option: ldap_id_use_start_tls
          value: 'true'
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - test_grep_domain.stdout is defined
        - test_grep_domain.stdout | length < 1
        - test_id_provider.stdout is defined
        - test_id_provider.stdout | length < 1

    - name: Set ldap_id_use_start_tls in sssd configuration
      ini_file:
        path: /etc/sssd/sssd.conf
        section: '{{ test_grep_domain.stdout | regex_replace(''\[(.*)\]'',''\1'')
          }}'
        option: ldap_id_use_start_tls
        value: 'true'
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - test_grep_domain.stdout is defined
        - test_grep_domain.stdout | length > 0
        - test_id_provider.stdout is defined
        - test_id_provider.stdout | length < 1
