# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Ensure invoking users password for privilege escalation when using sudo
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-83421-8
    - DISA-STIG-RHEL-07-010342
    - NIST-800-53-CM-6(b)
    - NIST-800-53-CM-6.1(iv)
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
    - sudoers_validate_passwd
  tasks:

    - name: Ensure that Defaults !targetpw is defined in sudoers
      lineinfile:
        path: /etc/sudoers
        create: true
        line: Defaults !targetpw
        state: present

    - name: Ensure that Defaults !rootpw is defined in sudoers
      lineinfile:
        path: /etc/sudoers
        create: true
        line: Defaults !rootpw
        state: present

    - name: Ensure that Defaults !runaspw is defined in sudoers
      lineinfile:
        path: /etc/sudoers
        create: true
        line: Defaults !runaspw
        state: present
