# platform = multi_platform_fedora,Red Hat Enterprise Linux 7,Red Hat Enterprise Linux 8
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Configure Polyinstantiation of /tmp Directories
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-83731-0
    - accounts_polyinstantiated_tmp
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
    - restrict_strategy
  tasks:

    - name: Create /tmp/tmp-inst directory
      file:
        path: /tmp/tmp-inst
        state: directory
        mode: '000'
        seuser: system_u
        serole: object_r
        setype: tmp_t

    - name: Make changes to /etc/security/namespace.conf
      lineinfile:
        path: /etc/security/namespace.conf
        create: false
        regexp: ^\s*/tmp\s+/tmp/tmp-inst/\s+level\s+root,adm$
        line: /tmp     /tmp/tmp-inst/        level      root,adm
        state: present
