# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Uninstall tftp-server Package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80213-2
    - DISA-STIG-RHEL-07-040700
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - disable_strategy
    - high_severity
    - low_complexity
    - low_disruption
    - no_reboot_needed
    - package_tftp-server_removed
  tasks:

    - name: Ensure tftp-server is removed
      package:
        name: tftp-server
        state: absent
