# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium
- name: Configure Maximum Number of Autoconfigured Addresses on All IPv6 Interfaces
    By Default
  hosts: '@@HOSTS@@'
  become: true
  vars:
    sysctl_net_ipv6_conf_default_max_addresses_value: '1'
  tags:
    - CCE-84256-7
    - disable_strategy
    - low_complexity
    - medium_disruption
    - reboot_required
    - sysctl_net_ipv6_conf_default_max_addresses
    - unknown_severity
  tasks:

    - name: Ensure sysctl net.ipv6.conf.default.max_addresses is set
      sysctl:
        name: net.ipv6.conf.default.max_addresses
        value: '{{ sysctl_net_ipv6_conf_default_max_addresses_value }}'
        state: present
        reload: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
