# platform = Red Hat Enterprise Linux 7,Red Hat Enterprise Linux 8,Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_sle
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Disable Ctrl-Alt-Del Reboot Activation
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-27511-5
    - DISA-STIG-RHEL-07-020230
    - NIST-800-171-3.4.5
    - NIST-800-53-AC-6(1)
    - NIST-800-53-CM-6(a)
    - disable_ctrlaltdel_reboot
    - disable_strategy
    - high_severity
    - low_complexity
    - low_disruption
    - no_reboot_needed
  tasks:

    - name: Disable Ctrl-Alt-Del Reboot Activation
      systemd:
        name: ctrl-alt-del.target
        masked: true
        state: stopped
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
