# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = true
# strategy = restrict
# complexity = medium
# disruption = low
- name: Enable SLUB/SLAB allocator poisoning
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82157-9
    - NIST-800-53-CM-6(a)
    - grub2_slub_debug_argument
    - low_disruption
    - medium_complexity
    - medium_severity
    - reboot_required
    - restrict_strategy
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: check slub_debug argument exists
      command: grep 'GRUB_CMDLINE_LINUX.*slub_debug=' /etc/default/grub
      failed_when: false
      register: argcheck
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'

    - name: replace existing slub_debug argument
      replace:
        path: /etc/default/grub
        regexp: slub_debug=\w+
        replace: slub_debug=P
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'
        - argcheck.rc == 0

    - name: add slub_debug argument
      replace:
        path: /etc/default/grub
        regexp: (GRUB_CMDLINE_LINUX=.*)"
        replace: \1 slub_debug=P"
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'
        - argcheck.rc != 0

    - name: update bootloader menu
      command: /sbin/grubby --update-kernel=ALL --args="slub_debug=P"
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'
