# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = true
# strategy = restrict
# complexity = medium
# disruption = low
- name: Enable page allocator poisoning
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82158-7
    - NIST-800-53-CM-6(a)
    - grub2_page_poison_argument
    - low_disruption
    - medium_complexity
    - medium_severity
    - reboot_required
    - restrict_strategy
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: check page_poison argument exists
      command: grep 'GRUB_CMDLINE_LINUX.*page_poison=' /etc/default/grub
      failed_when: false
      register: argcheck
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'

    - name: replace existing page_poison argument
      replace:
        path: /etc/default/grub
        regexp: page_poison=\w+
        replace: page_poison=1
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'
        - argcheck.rc == 0

    - name: add page_poison argument
      replace:
        path: /etc/default/grub
        regexp: (GRUB_CMDLINE_LINUX=.*)"
        replace: \1 page_poison=1"
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'
        - argcheck.rc != 0

    - name: update bootloader menu
      command: /sbin/grubby --update-kernel=ALL --args="page_poison=1"
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"grub2-common" in ansible_facts.packages'
