# platform = Red Hat Enterprise Linux 7,Red Hat Enterprise Linux 8,Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol
# reboot = false
# complexity = low
# strategy = configure
# disruption = low
- name: Enable SSH Server firewalld Firewall Exception
  hosts: '@@HOSTS@@'
  become: true
  vars:
    sshd_listening_port: '22'
  tags:
    - CCE-80361-9
    - NIST-800-171-3.1.12
    - NIST-800-53-AC-17(a)
    - NIST-800-53-CM-6(b)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - configure_strategy
    - firewalld_sshd_port_enabled
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
  tasks:

    - name: Ensure firewalld is installed
      package:
        name: '{{ item }}'
        state: present
      with_items:
        - firewalld
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Enable SSHD in firewalld (custom port)
      firewalld:
        port: '{{ sshd_listening_port }}/tcp'
        permanent: true
        state: enabled
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - sshd_listening_port != 22

    - name: Enable SSHD in firewalld (default port)
      firewalld:
        service: ssh
        permanent: true
        state: enabled
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - sshd_listening_port == 22
