# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = false
# strategy = configure
# complexity = low
# disruption = medium
- name: Set number of Password Hashing Rounds - password-auth
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_password_pam_unix_rounds: '65536'
  tags:
    - CCE-83402-8
    - accounts_password_pam_unix_rounds_password_auth
    - configure_strategy
    - low_complexity
    - medium_disruption
    - medium_severity
    - no_reboot_needed
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Configure number of password-auth password hashing rounds in pam_unix.so
      pamd:
        name: password-auth
        type: password
        control: sufficient
        module_path: pam_unix.so
        module_arguments: rounds={{ var_password_pam_unix_rounds }}
        state: args_present
      when: '"pam" in ansible_facts.packages'
