# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = true
# strategy = restrict
# complexity = medium
# disruption = low
- name: IOMMU configuration directive
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82351-8
    - grub2_enable_iommu_force
    - low_disruption
    - medium_complexity
    - reboot_required
    - restrict_strategy
    - unknown_severity
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: check iommu argument exists
      command: grep 'GRUB_CMDLINE_LINUX.*iommu=' /etc/default/grub
      failed_when: false
      register: argcheck
      when:
        - '"grub2-common" in ansible_facts.packages'
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]

    - name: replace existing iommu argument
      replace:
        path: /etc/default/grub
        regexp: iommu=\w+
        replace: iommu=force
      when:
        - '"grub2-common" in ansible_facts.packages'
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - argcheck.rc == 0

    - name: add iommu argument
      replace:
        path: /etc/default/grub
        regexp: (GRUB_CMDLINE_LINUX=.*)"
        replace: \1 iommu=force"
      when:
        - '"grub2-common" in ansible_facts.packages'
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - argcheck.rc != 0

    - name: update bootloader menu
      command: /sbin/grubby --update-kernel=ALL --args="iommu=force"
      when:
        - '"grub2-common" in ansible_facts.packages'
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
