# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium
- name: Enable Kernel Parameter to Use TCP RFC 1337 on IPv4 Interfaces
  hosts: '@@HOSTS@@'
  become: true
  vars:
    sysctl_net_ipv4_tcp_rfc1337_value: '1'
  tags:
    - CCE-84269-0
    - disable_strategy
    - low_complexity
    - medium_disruption
    - medium_severity
    - reboot_required
    - sysctl_net_ipv4_tcp_rfc1337
  tasks:

    - name: Ensure sysctl net.ipv4.tcp_rfc1337 is set
      sysctl:
        name: net.ipv4.tcp_rfc1337
        value: '{{ sysctl_net_ipv4_tcp_rfc1337_value }}'
        state: present
        reload: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
