# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium
- name: Configure maximum number of process identifiers
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-83365-7
    - disable_strategy
    - low_complexity
    - medium_disruption
    - medium_severity
    - reboot_required
    - sysctl_kernel_pid_max
  tasks:

    - name: Ensure sysctl kernel.pid_max is set to 65536
      sysctl:
        name: kernel.pid_max
        value: '65536'
        state: present
        reload: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
