# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Disable rexec Service
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-27408-4
    - NIST-800-171-3.1.13
    - NIST-800-171-3.4.7
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - NIST-800-53-IA-5(1)(c)
    - disable_strategy
    - high_severity
    - low_complexity
    - low_disruption
    - no_reboot_needed
    - service_rexec_disabled
  tasks:

    - name: Disable service rexec
      block:

        - name: Gather the service facts
          service_facts: null

        - name: Disable service rexec
          systemd:
            name: rexec.service
            enabled: 'no'
            state: stopped
            masked: 'yes'
          when: '"rexec.service" in ansible_facts.services'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Unit Socket Exists - rexec.socket
      command: systemctl list-unit-files rexec.socket
      args:
        warn: false
      register: socket_file_exists
      changed_when: false
      ignore_errors: true
      check_mode: false
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Disable socket rexec
      systemd:
        name: rexec.socket
        enabled: 'no'
        state: stopped
        masked: 'yes'
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"rexec.socket" in socket_file_exists.stdout_lines[1]'
