# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Uninstall rsh-server Package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-27342-5
    - DISA-STIG-RHEL-07-020000
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - NIST-800-53-IA-5(1)(c)
    - disable_strategy
    - high_severity
    - low_complexity
    - low_disruption
    - no_reboot_needed
    - package_rsh-server_removed
  tasks:

    - name: Ensure rsh-server is removed
      package:
        name: rsh-server
        state: absent
