# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Remove the GDM Package Group
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82348-4
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - disable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - package_gdm_removed
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Ensure gdm is removed
      package:
        name: gdm
        state: absent
      when: '"gdm" in ansible_facts.packages'
