# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Disable the xdm_sysadm_login SELinux Boolean
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_xdm_sysadm_login: 'false'
  tags:
    - CCE-82335-1
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - sebool_xdm_sysadm_login
  tasks:

    - name: Ensure libsemanage-python installed
      package:
        name: libsemanage-python
        state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Set SELinux boolean xdm_sysadm_login accordingly
      seboolean:
        name: xdm_sysadm_login
        state: '{{ var_xdm_sysadm_login }}'
        persistent: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
