# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Enable the OpenSSH Service
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80216-5
    - DISA-STIG-RHEL-07-040310
    - NIST-800-171-3.1.13
    - NIST-800-171-3.13.8
    - NIST-800-171-3.5.4
    - NIST-800-53-CM-6(a)
    - NIST-800-53-SC-8
    - NIST-800-53-SC-8(1)
    - NIST-800-53-SC-8(2)
    - NIST-800-53-SC-8(3)
    - NIST-800-53-SC-8(4)
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_sshd_enabled
  tasks:

    - name: Enable service sshd
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Enable service sshd
          service:
            name: sshd
            enabled: 'yes'
            state: started
            masked: 'no'
          when:
            - '"openssh-server" in ansible_facts.packages'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
