# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Disable KDump Kernel Crash Analyzer (kdump)
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80258-7
    - DISA-STIG-RHEL-07-021300
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - disable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_kdump_disabled
  tasks:

    - name: Disable service kdump
      block:

        - name: Gather the service facts
          service_facts: null

        - name: Disable service kdump
          systemd:
            name: kdump.service
            enabled: 'no'
            state: stopped
            masked: 'yes'
          when: '"kdump.service" in ansible_facts.services'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Unit Socket Exists - kdump.socket
      command: systemctl list-unit-files kdump.socket
      args:
        warn: false
      register: socket_file_exists
      changed_when: false
      ignore_errors: true
      check_mode: false
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Disable socket kdump
      systemd:
        name: kdump.socket
        enabled: 'no'
        state: stopped
        masked: 'yes'
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"kdump.socket" in socket_file_exists.stdout_lines[1]'
