# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Enable cron Service
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-27323-5
    - NIST-800-53-CM-6(a)
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_crond_enabled
  tasks:

    - name: Enable service crond
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Enable service crond
          service:
            name: crond
            enabled: 'yes'
            state: started
            masked: 'no'
          when:
            - '"cronie" in ansible_facts.packages'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
