# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Set Interactive Session Timeout
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_accounts_tmout: '900'
  tags:
    - CCE-27557-8
    - DISA-STIG-RHEL-07-040160
    - NIST-800-171-3.1.11
    - NIST-800-53-AC-12
    - NIST-800-53-AC-2(5)
    - NIST-800-53-CM-6(a)
    - NIST-800-53-SC-10
    - accounts_tmout
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
  tasks:

    - name: Set Interactive Session Timeout
      block:

        - name: Check for duplicate values
          lineinfile:
            path: /etc/profile.d/tmout.sh
            create: false
            regexp: ^\s*TMOUT=
            state: absent
          check_mode: true
          changed_when: false
          register: dupes

        - name: Deduplicate values from /etc/profile.d/tmout.sh
          lineinfile:
            path: /etc/profile.d/tmout.sh
            create: false
            regexp: ^\s*TMOUT=
            state: absent
          when: dupes.found is defined and dupes.found > 1

        - name: Insert correct line to /etc/profile.d/tmout.sh
          lineinfile:
            path: /etc/profile.d/tmout.sh
            create: true
            regexp: ^\s*TMOUT=
            line: TMOUT={{ var_accounts_tmout }}
            state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
