# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Verify Permissions on Backup shadow File
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-83416-8
    - configure_strategy
    - file_permissions_backup_etc_shadow
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
  tasks:

    - name: Test for existence /etc/shadow-
      stat:
        path: /etc/shadow-
      register: file_exists

    - name: Ensure permission 0000 on /etc/shadow-
      file:
        path: /etc/shadow-
        mode: '0000'
      when: file_exists.stat is defined and file_exists.stat.exists
