# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_rhel,multi_platform_ol,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Ensure the Default Umask is Set Correctly in login.defs
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_accounts_user_umask: '027'
  tags:
    - CCE-80205-8
    - DISA-STIG-RHEL-07-020240
    - NIST-800-53-AC-6(1)
    - NIST-800-53-CM-6(a)
    - accounts_umask_etc_login_defs
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Ensure the Default UMASK is Set Correctly
      lineinfile:
        create: true
        dest: /etc/login.defs
        regexp: ^UMASK
        line: UMASK {{ var_accounts_user_umask }}
      when: '"shadow-utils" in ansible_facts.packages'
