# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel
# reboot = false
# strategy = restrict
# complexity = low
# disruption = medium
- name: Ensure that Root's Path Does Not Include World or Group-Writable Directories
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80200-9
    - NIST-800-53-CM-6(a)
    - accounts_root_path_dirs_no_write
    - low_complexity
    - medium_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
  tasks:

    - name: Print error message if user is not root
      fail:
        msg: Root account required to read root $PATH
      when: ansible_env.USER != "root"
      ignore_errors: true

    - name: Get root paths which are not symbolic links
      stat:
        path: '{{ item }}'
      changed_when: false
      failed_when: false
      register: root_paths
      with_items: '{{ ansible_env.PATH.split('':'') }}'
      when: ansible_env.USER == "root"

    - name: Disable writability to root directories
      file:
        path: '{{ item.item }}'
        mode: g-w,o-w
      with_items: '{{ root_paths.results }}'
      when:
        - root_paths.results is defined
        - item.stat.exists
        - not item.stat.islnk
