# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Limit the Number of Concurrent Login Sessions Allowed Per User
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_accounts_max_concurrent_login_sessions: '1'
  tags:
    - CCE-82041-5
    - CJIS-5.5.2.2
    - DISA-STIG-RHEL-07-040000
    - NIST-800-53-AC-10
    - NIST-800-53-CM-6(a)
    - accounts_max_concurrent_login_sessions
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
    - restrict_strategy
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Find /etc/security/limits.d files containing maxlogins configuration
      find:
        paths: /etc/security/limits.d
        contains: ^[\s]*\*[\s]+(?:(?:hard)|(?:-))[\s]+maxlogins
        patterns: '*.conf'
      register: maxlogins
      when: '"pam" in ansible_facts.packages'

    - name: Limit the Number of Concurrent Login Sessions Allowed Per User in files
        from limits.d
      replace:
        dest: '{{ item.path }}'
        regexp: ^#?\*.*maxlogins.*
        replace: '*          hard    maxlogins     {{ var_accounts_max_concurrent_login_sessions
          }}'
      with_items:
        - '{{ maxlogins.files }}'
      when: '"pam" in ansible_facts.packages'

    - name: Limit the Number of Concurrent Login Sessions Allowed Per User
      lineinfile:
        state: present
        dest: /etc/security/limits.conf
        insertbefore: ^# End of file
        regexp: ^#?\*.*maxlogins
        line: '*          hard    maxlogins     {{ var_accounts_max_concurrent_login_sessions
          }}'
        create: true
      when:
        - '"pam" in ansible_facts.packages'
        - maxlogins.matched == 0
