# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = unknown
# complexity = low
# disruption = medium
- name: Disable WIFI Network Notification in GNOME3
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80119-1
    - NIST-800-171-3.1.16
    - dconf_gnome_disable_wifi_notification
    - low_complexity
    - medium_disruption
    - medium_severity
    - no_reboot_needed
    - unknown_strategy
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Disable WiFi Network Notification in GNOME3
      ini_file:
        dest: /etc/dconf/db/local.d/00-security-settings
        section: org/gnome/nm-applet
        option: suppress-wireless-networks-available
        value: 'true'
        create: true
        no_extra_spaces: true
      when:
        - '"gdm" in ansible_facts.packages'
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]

    - name: Prevent user modification of GNOME3 disablement of WiFi
      lineinfile:
        path: /etc/dconf/db/local.d/locks/00-security-settings-lock
        regexp: ^/org/gnome/nm-applet/suppress-wireless-networks-available$
        line: /org/gnome/nm-applet/suppress-wireless-networks-available
        create: true
      when:
        - '"gdm" in ansible_facts.packages'
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]

    - name: Dconf Update
      command: dconf update
      when:
        - '"gdm" in ansible_facts.packages'
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
