# platform = Red Hat Virtualization 4,Red Hat Enterprise Linux 7,Red Hat Enterprise Linux 8,Fedora,Oracle Linux 7,Oracle Linux 8,WRLinux 1019
# reboot = false
# strategy = restrict
# complexity = low
# disruption = medium
- name: Ensure All World-Writable Directories Are Owned by root user
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-83374-9
    - dir_perms_world_writable_root_owned
    - low_complexity
    - medium_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
  tasks:

    - name: Configure excluded (non local) file systems
      set_fact:
        excluded_fstypes:
          - afs
          - ceph
          - cifs
          - smb3
          - smbfs
          - sshfs
          - ncpfs
          - ncp
          - nfs
          - nfs4
          - gfs
          - gfs2
          - glusterfs
          - gpfs
          - pvfs2
          - ocfs2
          - lustre
          - davfs
          - fuse.sshfs

    - name: Create empty list of excluded paths
      set_fact:
        excluded_paths: []

    - name: Detect nonlocal file systems and add them to excluded paths
      set_fact:
        excluded_paths: '{{ excluded_paths | union([item.mount]) }}'
      loop: '{{ ansible_mounts }}'
      when: item.fstype in excluded_fstypes

    - name: Find all directories excluding non-local partitions
      find:
        paths: /
        excludes: excluded_paths
        file_type: directory
        hidden: true
        recurse: true
      register: found_dirs

    - name: Create list of world writable directories
      set_fact:
        world_writable_dirs: '{{ found_dirs.files | selectattr(''woth'') | list }}'

    - name: Change owner to root on directories which are world writable
      file:
        path: '{{ item.path }}'
        owner: root
      loop: '{{ world_writable_dirs }}'
      ignore_errors: true
