# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Verify Group Who Owns /var/log Directory
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - configure_strategy
    - file_groupowner_var_log
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
  tasks:

    - name: Test for existence /var/log/
      stat:
        path: /var/log/
      register: file_exists

    - name: Ensure group owner 0 on /var/log/
      file:
        path: /var/log/
        group: '0'
      when: file_exists.stat is defined and file_exists.stat.exists
