# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Verify the UEFI Boot Loader grub.cfg Permissions
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-83431-7
    - NIST-800-171-3.4.5
    - NIST-800-53-AC-6(1)
    - NIST-800-53-CM-6(a)
    - configure_strategy
    - file_permissions_efi_grub2_cfg
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
  tasks:

    - name: Test for existence /boot/efi/EFI/redhat/grub.cfg
      stat:
        path: /boot/efi/EFI/redhat/grub.cfg
      register: file_exists
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Ensure permission 0700 on /boot/efi/EFI/redhat/grub.cfg
      file:
        path: /boot/efi/EFI/redhat/grub.cfg
        mode: '0700'
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - file_exists.stat is defined and file_exists.stat.exists
