# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Remove Rsh Trust Files
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-27406-8
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - high_severity
    - low_complexity
    - low_disruption
    - no_reboot_needed
    - no_rsh_trust_files
    - restrict_strategy
  tasks:
    - block:

        - name: Detect .rhosts files in users home directories
          find:
            paths:
              - /root
              - /home
            recurse: true
            patterns: .rhosts
            hidden: true
            file_type: file
          check_mode: false
          register: rhosts_locations

        - name: Remove .rhosts files
          file:
            path: '{{ item }}'
            state: absent
          with_items: '{{ rhosts_locations.files | map(attribute=''path'') | list
            }}'
          when: rhosts_locations is success

        - name: Remove /etc/hosts.equiv file
          file:
            path: /etc/hosts.equiv
            state: absent
