# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Uninstall quagga Package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-27594-1
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - disable_strategy
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
    - package_quagga_removed
  tasks:

    - name: Ensure quagga is removed
      package:
        name: quagga
        state: absent
