# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Remove the Kerberos Server Package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - disable_strategy
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
    - package_krb5-server_removed
  tasks:

    - name: Ensure krb5-server is removed
      package:
        name: krb5-server
        state: absent
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
