# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Install the pcsc-lite package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82347-6
    - NIST-800-53-CM-6(a)
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - package_pcsc-lite_installed
  tasks:

    - name: Ensure pcsc-lite is installed
      package:
        name: pcsc-lite
        state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
