# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Ensure the default plugins for the audit dispatcher are Installed
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - package_audit-audispd-plugins_installed
  tasks:

    - name: Ensure audit-audispd-plugins is installed
      package:
        name: audit-audispd-plugins
        state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
