# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Install the SSSD Package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80362-7
    - NIST-800-53-CM-6(a)
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - package_sssd_installed
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Ensure sssd is installed
      package:
        name: sssd
        state: present
      when: '"sssd-common" in ansible_facts.packages'
