# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Uninstall the ssl compliant telnet server
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - disable_strategy
    - high_severity
    - low_complexity
    - low_disruption
    - no_reboot_needed
    - package_telnetd-ssl_removed
  tasks:

    - name: Ensure telnetd-ssl is removed
      package:
        name: telnetd-ssl
        state: absent
