# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Install the psacct package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82403-7
    - NIST-800-53-AU-12(a)
    - NIST-800-53-CM-6(a)
    - enable_strategy
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
    - package_psacct_installed
  tasks:

    - name: Ensure psacct is installed
      package:
        name: psacct
        state: present
