# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Remove the FreeRadius Server Package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82751-9
    - disable_strategy
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
    - package_freeradius_removed
  tasks:

    - name: Ensure freeradius is removed
      package:
        name: freeradius
        state: absent
