# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Install vim Package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82957-2
    - enable_strategy
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
    - package_vim_installed
  tasks:

    - name: Ensure vim-enhanced is installed
      package:
        name: vim-enhanced
        state: present
