# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Install tar Package
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-82966-3
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - package_tar_installed
  tasks:

    - name: Ensure tar is installed
      package:
        name: tar
        state: present
