# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Disable the logging_syslogd_can_sendmail SELinux Boolean
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_logging_syslogd_can_sendmail: 'false'
  tags:
    - CCE-82299-9
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - sebool_logging_syslogd_can_sendmail
  tasks:

    - name: Ensure libsemanage-python installed
      package:
        name: libsemanage-python
        state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Set SELinux boolean logging_syslogd_can_sendmail accordingly
      seboolean:
        name: logging_syslogd_can_sendmail
        state: '{{ var_logging_syslogd_can_sendmail }}'
        persistent: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
