# platform = multi_platform_all
# reboot = true
# strategy = patch
# complexity = low
# disruption = high
- name: Ensure Software Patches Installed
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-26895-3
    - CJIS-5.10.4.1
    - DISA-STIG-RHEL-07-020260
    - NIST-800-53-CM-6(a)
    - NIST-800-53-SI-2(5)
    - NIST-800-53-SI-2(c)
    - PCI-DSS-Req-6.2
    - high_disruption
    - high_severity
    - low_complexity
    - patch_strategy
    - reboot_required
    - security_patches_up_to_date
    - skip_ansible_lint
  tasks:

    - name: Security patches are up to date
      package:
        name: '*'
        state: latest
