# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Enable nails Service
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80128-2
    - NIST-800-53-CM-6(a)
    - NIST-800-53-SC-28
    - NIST-800-53-SI-3(a)
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_nails_enabled
  tasks:

    - name: Enable service nails
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Enable service nails
          service:
            name: nails
            enabled: 'yes'
            state: started
            masked: 'no'
          when:
            - '"nails" in ansible_facts.packages'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
