# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Disable Network File System Lock Service (nfslock)
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80228-0
    - disable_strategy
    - low_complexity
    - low_disruption
    - no_reboot_needed
    - service_nfslock_disabled
    - unknown_severity
  tasks:

    - name: Disable service nfslock
      block:

        - name: Gather the service facts
          service_facts: null

        - name: Disable service nfslock
          systemd:
            name: nfslock.service
            enabled: 'no'
            state: stopped
            masked: 'yes'
          when: '"nfslock.service" in ansible_facts.services'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Unit Socket Exists - nfslock.socket
      command: systemctl list-unit-files nfslock.socket
      args:
        warn: false
      register: socket_file_exists
      changed_when: false
      ignore_errors: true
      check_mode: false
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Disable socket nfslock
      systemd:
        name: nfslock.socket
        enabled: 'no'
        state: stopped
        masked: 'yes'
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"nfslock.socket" in socket_file_exists.stdout_lines[1]'
