# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Verify ip6tables Enabled if Using IPv6
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - NIST-800-53-AC-4
    - NIST-800-53-CA-3(5)
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(b)
    - NIST-800-53-SC-7(21)
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_ip6tables_enabled
  tasks:

    - name: Enable service ip6tables
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Enable service ip6tables
          service:
            name: ip6tables
            enabled: 'yes'
            state: started
            masked: 'no'
          when:
            - '"iptables-ipv6" in ansible_facts.packages'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
