# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Disable httpd Service
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80300-7
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - disable_strategy
    - low_complexity
    - low_disruption
    - no_reboot_needed
    - service_httpd_disabled
    - unknown_severity
  tasks:

    - name: Disable service httpd
      block:

        - name: Gather the service facts
          service_facts: null

        - name: Disable service httpd
          systemd:
            name: httpd.service
            enabled: 'no'
            state: stopped
            masked: 'yes'
          when: '"httpd.service" in ansible_facts.services'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Unit Socket Exists - httpd.socket
      command: systemctl list-unit-files httpd.socket
      args:
        warn: false
      register: socket_file_exists
      changed_when: false
      ignore_errors: true
      check_mode: false
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Disable socket httpd
      systemd:
        name: httpd.socket
        enabled: 'no'
        state: stopped
        masked: 'yes'
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"httpd.socket" in socket_file_exists.stdout_lines[1]'
