# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Disable Advanced Configuration and Power Interface (acpid)
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80252-0
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - disable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_acpid_disabled
  tasks:

    - name: Disable service acpid
      block:

        - name: Gather the service facts
          service_facts: null

        - name: Disable service acpid
          systemd:
            name: acpid.service
            enabled: 'no'
            state: stopped
            masked: 'yes'
          when: '"acpid.service" in ansible_facts.services'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Unit Socket Exists - acpid.socket
      command: systemctl list-unit-files acpid.socket
      args:
        warn: false
      register: socket_file_exists
      changed_when: false
      ignore_errors: true
      check_mode: false
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Disable socket acpid
      systemd:
        name: acpid.socket
        enabled: 'no'
        state: stopped
        masked: 'yes'
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"acpid.socket" in socket_file_exists.stdout_lines[1]'
