# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Enable the SSSD Service
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80363-5
    - NIST-800-53-CM-6(a)
    - NIST-800-53-IA-5(10)
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_sssd_enabled
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Enable service sssd
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Enable service sssd
          service:
            name: sssd
            enabled: 'yes'
            state: started
            masked: 'no'
          when:
            - '"sssd" in ansible_facts.packages'
      when:
        - '"sssd-common" in ansible_facts.packages'
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
