# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Enable syslog-ng Service
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - NIST-800-53-AU-4(1)
    - NIST-800-53-CM-6(a)
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_syslogng_enabled
  tasks:

    - name: Enable service syslogng
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Enable service syslogng
          service:
            name: syslogng
            enabled: 'yes'
            state: started
            masked: 'no'
          when:
            - '"syslogng" in ansible_facts.packages'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
