# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: The Chronyd service is enabled
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-83420-0
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_chronyd_enabled
  tasks:

    - name: Enable service chronyd
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Enable service chronyd
          service:
            name: chronyd
            enabled: 'yes'
            state: started
            masked: 'no'
          when:
            - '"chrony" in ansible_facts.packages'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
