# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Disable Network File System (nfs)
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80237-1
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - disable_strategy
    - low_complexity
    - low_disruption
    - no_reboot_needed
    - service_nfs_disabled
    - unknown_severity
  tasks:

    - name: Disable service nfs-server
      block:

        - name: Gather the service facts
          service_facts: null

        - name: Disable service nfs-server
          systemd:
            name: nfs-server.service
            enabled: 'no'
            state: stopped
            masked: 'yes'
          when: '"nfs-server.service" in ansible_facts.services'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Unit Socket Exists - nfs-server.socket
      command: systemctl list-unit-files nfs-server.socket
      args:
        warn: false
      register: socket_file_exists
      changed_when: false
      ignore_errors: true
      check_mode: false
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Disable socket nfs-server
      systemd:
        name: nfs-server.socket
        enabled: 'no'
        state: stopped
        masked: 'yes'
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"nfs-server.socket" in socket_file_exists.stdout_lines[1]'
