# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Enable IRQ Balance (irqbalance)
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80257-9
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - enable_strategy
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
    - service_irqbalance_enabled
  tasks:

    - name: Enable service irqbalance
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Enable service irqbalance
          service:
            name: irqbalance
            enabled: 'yes'
            state: started
            masked: 'no'
          when:
            - '"irqbalance" in ansible_facts.packages'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
