# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Disable Red Hat Network Service (rhnsd)
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80269-4
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - disable_strategy
    - low_complexity
    - low_disruption
    - low_severity
    - no_reboot_needed
    - service_rhnsd_disabled
  tasks:

    - name: Disable service rhnsd
      block:

        - name: Gather the service facts
          service_facts: null

        - name: Disable service rhnsd
          systemd:
            name: rhnsd.service
            enabled: 'no'
            state: stopped
            masked: 'yes'
          when: '"rhnsd.service" in ansible_facts.services'
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Unit Socket Exists - rhnsd.socket
      command: systemctl list-unit-files rhnsd.socket
      args:
        warn: false
      register: socket_file_exists
      changed_when: false
      ignore_errors: true
      check_mode: false
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Disable socket rhnsd
      systemd:
        name: rhnsd.socket
        enabled: 'no'
        state: stopped
        masked: 'yes'
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
          "container"]
        - '"rhnsd.socket" in socket_file_exists.stdout_lines[1]'
