# platform = debian 10,debian 9,multi_platform_fedora,Oracle Linux 7,Oracle Linux 8,Red Hat Enterprise Linux 7,Red Hat Enterprise Linux 8,WRLinux 1019
# reboot = false
# strategy = configure
# complexity = low
# disruption = medium
- name: Ensure Default SNMP Password Is Not Used
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_snmpd_ro_string: changemero
    var_snmpd_rw_string: changemerw
  tags:
    - CCE-27386-2
    - DISA-STIG-RHEL-07-040800
    - NIST-800-53-IA-5(e)
    - configure_strategy
    - high_severity
    - low_complexity
    - medium_disruption
    - no_reboot_needed
    - snmpd_not_default_password
  tasks:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Check if file /etc/snmp/snmpd.conf exists
      stat:
        path: /etc/snmp/snmpd.conf
      register: snmpd
      when: '"net-snmp" in ansible_facts.packages'

    - name: Replace all instances of SNMP RO strings
      replace:
        path: /etc/snmp/snmpd.conf
        regexp: public
        replace: '{{ var_snmpd_ro_string }}'
      when:
        - '"net-snmp" in ansible_facts.packages'
        - (snmpd.stat.exists is defined and snmpd.stat.exists)

    - name: Replace all instances of SNMP RW strings
      replace:
        path: /etc/snmp/snmpd.conf
        regexp: private
        replace: '{{ var_snmpd_rw_string }}'
      when:
        - '"net-snmp" in ansible_facts.packages'
        - (snmpd.stat.exists is defined and snmpd.stat.exists)
