# platform = Red Hat Enterprise Linux 7,Oracle Linux 7,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Use Only FIPS 140-2 Validated Ciphers
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-83398-8
    - DISA-STIG-RHEL-07-040110
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
    - sshd_use_approved_ciphers_ordered_stig
  tasks:

    - name: Configure sshd to use approved ciphers
      lineinfile:
        path: /etc/ssh/sshd_config
        line: Ciphers aes256-ctr,aes192-ctr,aes128-ctr
        state: present
        regexp: ^[\s]*[Cc]iphers[\s]+(aes256-ctr(?=[\w,-@]+|$),?)?(aes192-ctr(?=[\w,-@]+|$),?)?(aes128-ctr(?=[\w,-@]+|$),?)?[\s]*(?:#.*)?$
        create: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
