# platform = Red Hat Enterprise Linux 7,Oracle Linux 7,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Use Only FIPS 140-2 Validated MACs
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-83636-1
    - DISA-STIG-RHEL-07-040400
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
    - sshd_use_approved_macs_ordered_stig
  tasks:

    - name: Configure sshd to use approved MACs
      lineinfile:
        path: /etc/ssh/sshd_config
        line: MACs hmac-sha2-512,hmac-sha2-256
        state: present
        regexp: ^[\s]*MACs[\s]+(hmac-sha2-512(?=[\w,-@]+|$),?)?(hmac-sha2-256(?=[\w,-@]+|$),?)?[\s]*(?:#.*)?$
        create: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
