# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium
- name: Disable IPv6 Addressing on IPv6 Interfaces by Default
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-85975-1
    - NIST-800-171-3.1.20
    - NIST-800-53-CM-6(a)
    - NIST-800-53-CM-7(a)
    - NIST-800-53-CM-7(b)
    - disable_strategy
    - low_complexity
    - medium_disruption
    - medium_severity
    - reboot_required
    - sysctl_net_ipv6_conf_default_disable_ipv6
  tasks:

    - name: Ensure sysctl net.ipv6.conf.default.disable_ipv6 is set to 1
      sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: '1'
        state: present
        reload: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
