# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium
- name: Configure Kernel to Rate Limit Sending of Duplicate TCP Acknowledgments
  hosts: '@@HOSTS@@'
  become: true
  vars:
    sysctl_net_ipv4_tcp_invalid_ratelimit_value: '500'
  tags:
    - CCE-82893-9
    - DISA-STIG-RHEL-07-040510
    - NIST-800-53-SC-5
    - disable_strategy
    - low_complexity
    - medium_disruption
    - medium_severity
    - reboot_required
    - sysctl_net_ipv4_tcp_invalid_ratelimit
  tasks:

    - name: Ensure sysctl net.ipv4.tcp_invalid_ratelimit is set
      sysctl:
        name: net.ipv4.tcp_invalid_ratelimit
        value: '{{ sysctl_net_ipv4_tcp_invalid_ratelimit_value }}'
        state: present
        reload: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
