# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium
- name: Configure Accepting Prefix Information in Router Advertisements on All IPv6
    Interfaces
  hosts: '@@HOSTS@@'
  become: true
  vars:
    sysctl_net_ipv6_conf_all_accept_ra_pinfo_value: '0'
  tags:
    - CCE-84279-9
    - disable_strategy
    - low_complexity
    - medium_disruption
    - reboot_required
    - sysctl_net_ipv6_conf_all_accept_ra_pinfo
    - unknown_severity
  tasks:

    - name: Ensure sysctl net.ipv6.conf.all.accept_ra_pinfo is set
      sysctl:
        name: net.ipv6.conf.all.accept_ra_pinfo
        value: '{{ sysctl_net_ipv6_conf_all_accept_ra_pinfo_value }}'
        state: present
        reload: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
