# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium
- name: Configure Auto Configuration on All IPv6 Interfaces
  hosts: '@@HOSTS@@'
  become: true
  vars:
    sysctl_net_ipv6_conf_all_autoconf_value: '0'
  tags:
    - CCE-84265-8
    - disable_strategy
    - low_complexity
    - medium_disruption
    - reboot_required
    - sysctl_net_ipv6_conf_all_autoconf
    - unknown_severity
  tasks:

    - name: Ensure sysctl net.ipv6.conf.all.autoconf is set
      sysctl:
        name: net.ipv6.conf.all.autoconf
        value: '{{ sysctl_net_ipv6_conf_all_autoconf_value }}'
        state: present
        reload: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
