# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Install the opensc Package For Multifactor Authentication
  hosts: '@@HOSTS@@'
  become: true
  tags:
    - CCE-80568-9
    - NIST-800-53-CM-6(a)
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - package_opensc_installed
  tasks:

    - name: Ensure opensc is installed
      package:
        name: opensc
        state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
