# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Enable the fips_mode SELinux Boolean
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_fips_mode: 'true'
  tags:
    - CCE-80418-7
    - NIST-800-171-3.13.11
    - NIST-800-53-CM-6(a)
    - NIST-800-53-IA-7
    - NIST-800-53-SC-12
    - NIST-800-53-SC-12(2)
    - NIST-800-53-SC-12(3)
    - NIST-800-53-SC-13
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - sebool_fips_mode
  tasks:

    - name: Ensure libsemanage-python installed
      package:
        name: libsemanage-python
        state: present
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]

    - name: Set SELinux boolean fips_mode accordingly
      seboolean:
        name: fips_mode
        state: '{{ var_fips_mode }}'
        persistent: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
