# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Configure auditd flush priority
  hosts: '@@HOSTS@@'
  become: true
  vars:
    var_auditd_flush: incremental_async
  tags:
    - CCE-27331-8
    - NIST-800-171-3.3.1
    - NIST-800-53-AU-11
    - NIST-800-53-CM-6(a)
    - auditd_data_retention_flush
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
  tasks:

    - name: Configure auditd Flush Priority
      lineinfile:
        dest: /etc/audit/auditd.conf
        regexp: ^\s*flush\s*=\s*.*$
        line: flush = {{ var_auditd_flush }}
        state: present
        create: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman",
        "container"]
